# NUMPY: Exercícios de Aplicação e Avaliação I
Exercício de aplicação dos conhecimentos adquiridos sobre a biblioteca Python/Numpy.

1. Comece por importar a biblioteca  'numpy' (da forma tradicional), necessária para poder abordar as questões seguintes.

In [1]:
import numpy as np

2. Crie um VECTOR (array de 1 dimensão), cuja visualização seja:

   **array([5, 10, 15, 20, 25])**

   Guarde o resultado numa variável com o nome "vector" e mostre o seu conteúdo.

In [56]:
vector = np.array([5, 10, 15, 20, 25])
print(vector)

[ 5 10 15 20 25]


3. Durante as aulas vimos algumas funções que permitem criar vectores e matrizes e outras estruturas mais complexas com um valor a preencher os espaços... ex: 'np.ones()' e 'np.zeros()'.

   Uma outra função do Numpy interessante é a que permite criar uma estrutura semelhante às anteriores, mas em que podemos escolher nós o valor que queremos que seja preenchido: **np.full()**.

   Crie uma matriz 4x5 (4 linhas e 5 colunas) de valores boleanos 'True' e mostre o seu conteúdo.

In [3]:
boolean_matrix = np.full((4, 5), True)
print(boolean_matrix)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


4. Crie uma matriz c/ esse mesmo ('matriz') nome e uma configuração 3x5, em que os seus valores sejam **números inteiros aleatórios** no intervalo entre -20, e 20, e mostre o resultado.

In [57]:
matriz = np.random.randint(-20, 21, size=(3, 5))
print(matriz)

[[  9 -13  -6   1 -12]
 [ 15  -1  -5   5 -14]
 [  7  15  17   9   3]]


5. Utilizando as funções **vstack()** e **hstack()**, construa duas matrizes resultado à custa da "junção" vertical (em primeiro lugar) e horizontal (em segundo lugar) entre as variáveis 'matriz' e 'vector' (por esta ordem). Mostre os respetivos resultados.

In [55]:
# Vetor
vector = np.array([5, 10, 15, 20, 25])
print("Vector:")
print(vector)

# Matriz com o mesmo número de colunas que o vetor
matriz = np.random.randint(-20, 21, size=(5, len(vector)))
print("\nMatriz:")
print(matriz)

# Junção vertical (vstack) entre a matriz e o vetor
matriz_vertical = np.vstack((matriz, vector))

# Junção horizontal (hstack) entre a matriz e o vetor
matriz_horizontal = np.hstack((matriz, vector.reshape(-1, 1)))

# Mostrar os resultados
print("\nMatriz Resultante após Junção Vertical:")
print(matriz_vertical)

print("\nMatriz Resultante após Junção Horizontal:")
print(matriz_horizontal)


Vector:
[ 5 10 15 20 25]

Matriz:
[[ 17   5  13   1  12]
 [ 13  -3  -7 -15 -14]
 [ 16 -10 -12  -2 -11]
 [-18   0  -6   0 -17]
 [-19  14   5 -15 -11]]

Matriz Resultante após Junção Vertical:
[[ 17   5  13   1  12]
 [ 13  -3  -7 -15 -14]
 [ 16 -10 -12  -2 -11]
 [-18   0  -6   0 -17]
 [-19  14   5 -15 -11]
 [  5  10  15  20  25]]

Matriz Resultante após Junção Horizontal:
[[ 17   5  13   1  12   5]
 [ 13  -3  -7 -15 -14  10]
 [ 16 -10 -12  -2 -11  15]
 [-18   0  -6   0 -17  20]
 [-19  14   5 -15 -11  25]]


6. Explique na célula a seguir por palavras suas este ☝️ último output.

Resposta: As variáveis vector e matriz não tinham tamanhos compatíveis para a junção horizontal ser feita, por isso o programa estava a dar erro. Para resolver criei as variáveis com o tamanho correto para apresentar a junção vertical e horizontal.

7. Usando a variável 'matriz' anterior, obtenha o valor correspondente ao centro da matriz (em linha e coluna).

In [20]:
# Usar a matriz criada anteriormente
matriz = np.random.randint(-20, 21, size=(3, 5))

# Obter as dimensões da matriz
num_linhas, num_colunas = matriz.shape

# Calcular as coordenadas do centro
linha_centro = num_linhas // 2
coluna_centro = num_colunas // 2

# Obter o valor no centro da matriz
valor_centro = matriz[linha_centro, coluna_centro]

# Mostrar o resultado
print("Matriz:")
print(matriz)

print("\nValor no Centro da Matriz:")
print(valor_centro)


Matriz:
[[ -8  -9   3  20   3]
 [-14  16 -18   2   8]
 [-13  13  -1  16 -18]]

Valor no Centro da Matriz:
-18


8. Crie uma matriz, de nome 'matriz2', com a configuração 4x5 e o seguinte conteúdo: **5,  10,  15,  20,  25, 8,   3,  17, -18,  -1, 12,   5, -15, -11,  -2, 1,  17,   7,  -5,  11.**

In [21]:
conteudo_matriz2 = [5, 10, 15, 20, 25, 8, 3, 17, -18, -1, 12, 5, -15, -11, -2, 1, 17, 7, -5, 11]
matriz2 = np.array(conteudo_matriz2).reshape(4, 5)
print(matriz2)

[[  5  10  15  20  25]
 [  8   3  17 -18  -1]
 [ 12   5 -15 -11  -2]
 [  1  17   7  -5  11]]


9. Escreva o código necessário (mínimo indispensável) para, a partir da 'matriz2', poder obter o seguinte *output*:
    
<pre>
array([[-15, -11],
       [  7,  -5]])
</pre>

In [23]:
# "matriz2[2:, 2:4]" seleciona as linhas a partir da terceira até o final e as colunas a partir da terceira até o final.
output_desejado = matriz2[2:, 2:4]
# Mostrar o output
print(output_desejado)

[[-15 -11]
 [  7  -5]]


10. Usando a variável 'vector' anterior, obtenha o seguinte resultado, com apenas uma instrução e uma condição:
    
    <pre>
        array([10, 20])
    </pre>

In [26]:
resultado = vector[(vector == 10) | (vector == 20)]
print(resultado)

[10 20]


11. Usando a função **np.arange()**, construa o seguinte vector, guarde-o numa variável 'vec1' e mostre o seu conteúdo **(observe bem o conteúdo)**:
    
    <pre>
        array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])
    </pre>

In [28]:
vec1 = np.arange(-10, 10, 1)
print(vec1)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


12. Escreva o código necessário para obter um vector com todos os números ímpares, <u>a partir de 'vec1'</u>.

In [30]:
# "vec1 % 2 != 0" cria uma máscara booleana que é True para os elementos ímpares e False para os elementos pares.
vec1 = np.arange(-10, 10, 1)
vec_impares = vec1[vec1 % 2 != 0]
print(vec_impares)

[-9 -7 -5 -3 -1  1  3  5  7  9]


13. Escreva o código para obter um segundo vector a partir de 'vec1', em que que todos os valores ímpares (ver a condição anterior) são substituídos pelo valor 0 (zero). Apresente ambos os vectores.

In [31]:
vec1 = np.arange(-10, 10, 1)

# Criar um segundo vetor substituindo os valores ímpares por zero
vec2 = vec1.copy()  # Crie uma cópia para evitar modificar o vetor original
vec2[vec2 % 2 != 0] = 0

# Mostrar ambos os vetores
print("Vec1:")
print(vec1)

print("\nVec2 (valores ímpares substituídos por zero):")
print(vec2)

Vec1:
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]

Vec2 (valores ímpares substituídos por zero):
[-10   0  -8   0  -6   0  -4   0  -2   0   0   0   2   0   4   0   6   0
   8   0]


14. Usando as funções np.repeat(), np.tile() e np.hstack(), usando apenas uma linha de código, apresente o seguinte resultado **(observe bem o conteúdo)**:
    
    <pre>
        array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
    </pre>

In [32]:
resultado = np.hstack((np.repeat(np.arange(1, 4), 3), np.tile(np.arange(1, 4), 3)))
print(resultado)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


15. Voltando à 'matriz2'... Se quisermos inverter a ordem das colunas, usando apenas a reindexação (ou seja, manipulando apenas os índices entre parênteses rectos em que a última coluna passa a ser a primeira, a penúltima passa a ser a segunda, etc. assim por diante, podemos usar a seguinte técnica:

In [36]:
matriz2 = np.array([[5, 10, 15, 20, 25],
                    [8, 3, 17, -18, -1],
                    [12, 5, -15, -11, -2],
                    [1, 17, 7, -5, 11]])

# Inverter a ordem das colunas
matriz2_invertida = matriz2[:, ::-1]

# Mostrar a matriz original e a matriz invertida
print("Matriz invertida:")
print(matriz2_invertida)

Matriz invertida:
[[ 25  20  15  10   5]
 [ -1 -18  17   3   8]
 [ -2 -11 -15   5  12]
 [ 11  -5   7  17   1]]


Usando o mesmo princípio, como faria para fazer a inversão das linhas (em vez das colunas)?

In [34]:
matriz2 = np.array([[5, 10, 15, 20, 25],
                    [8, 3, 17, -18, -1],
                    [12, 5, -15, -11, -2],
                    [1, 17, 7, -5, 11]])

# Inverter a ordem das linhas
matriz2_invertida_linhas = matriz2[::-1, :]

# Mostrar a matriz original e a matriz com as linhas invertidas
print("Matriz Original:")
print(matriz2)

print("\nMatriz Invertida nas Linhas:")
print(matriz2_invertida_linhas)

Matriz Original:
[[  5  10  15  20  25]
 [  8   3  17 -18  -1]
 [ 12   5 -15 -11  -2]
 [  1  17   7  -5  11]]

Matriz Invertida nas Linhas:
[[  1  17   7  -5  11]
 [ 12   5 -15 -11  -2]
 [  8   3  17 -18  -1]
 [  5  10  15  20  25]]


16. Explique, usando palavras suas, a diferença entre filtrar registos usando o método de indexação (c/ a condição entre parêteses rectos) e o método usando a instrução where().

Resposta: A indexação com condição entre colchetes retorna diretamente os elementos que satisfazem a condição. Já oO método where() retorna os índices onde a condição é verdadeira, exigindo uma etapa adicional para obter os elementos correspondentes usando esses índices.

17. Ao executar a instrução **outra_matriz = np.sort(matriz, axis=0)**, explique o que vai conter a variavel 'outra_matriz'. (execute a instrução, avalie o resultado e explique)

In [39]:
# Usar a seguinte matriz:
matriz = np.array([[3, 1, 4],
                   [1, 5, 9],
                   [2, 6, 5]])
outra_matriz = np.sort(matriz, axis=0)
print(outra_matriz)

[[1 1 4]
 [2 5 5]
 [3 6 9]]


Resposta: A função numpy.sort() é útil em situações em que é necessário obter os elementos em uma ordem específica, seja em ordem crescente ou decrescente. Portanto, a variável outra_matriz conterá a matriz original, mas com cada coluna ordenada independentemente, mantendo a relação entre os elementos de cada linha.

18. Por que razão a instrução anterior deve ser usada com bastante cuidado? Ou seja, em que tipo de riscos/problemas podemos incorrer ao usá-la?

Resposta: A função numpy.sort() deve ser usada com cuidado devido a vários motivos. Primeiro, ela retorna um novo array ordenado, podendo levar a alterações indesejadas no array original se não for tratada com atenção. Além disso, a desordem de índices, o desempenho, a escolha do eixo de ordenação e a presença de tipos mistos ou objetos podem gerar resultados inesperados. É essencial compreender as implicações da ordenação, considerar a correspondência de índices e garantir que o uso seja adequado ao contexto específico para evitar problemas de interpretação e manipulação dos dados.

19. Que técnica alternativa (estudada em aula) poderíamos usar, apenas com recurso à biblioteca Numpy, para podermos ordenar a nossa matriz usando como referência a primeira coluna, sem incorrer nos riscos/problemas mencionados na pergunta anterior? (escreva o código, execute e verifique o resultado em comparação com a 'matriz' original)

In [41]:
# Ao usar np.argsort() é possível obter a matriz ordenada com base na primeira coluna sem alterar a matriz original e sem os riscos associados à ordenação direta.

# Supondo que esta seja a matriz original
matriz = np.array([[3, 1, 4],
                   [1, 5, 9],
                   [2, 6, 5]])

# Obter índices de ordenação com base na primeira coluna
indices_ordenacao = np.argsort(matriz[:, 0])

# Aplicar os índices para obter a matriz ordenada
matriz_ordenada = matriz[indices_ordenacao]

# Mostrar a matriz original e a matriz ordenada
print("Matriz Original:")
print(matriz)

print("\nMatriz Ordenada com Base na Primeira Coluna:")
print(matriz_ordenada)


Matriz Original:
[[3 1 4]
 [1 5 9]
 [2 6 5]]

Matriz Ordenada com Base na Primeira Coluna:
[[1 5 9]
 [2 6 5]
 [3 1 4]]


20. Crie 2 vectores (1-dimensão), usando a função 'randint' do Numpy, e guarde cada um na sua variável. O primeiro vector deverá ter 20 números e o segundo 25... ambos com inteiros entre -10 e 10. Use a função **np.intersect1d('primeiro vector', 'segundo vector')**, substituindo os parâmetros pelos nomes que deu a cada uma das suas variáveis, e explique o resultado.

In [42]:
# Criar o primeiro vetor com 20 números inteiros entre -10 e 10
primeiro_vector = np.random.randint(-10, 11, size=20)

# Criar o segundo vetor com 25 números inteiros entre -10 e 10
segundo_vector = np.random.randint(-10, 11, size=25)

# Encontrar a interseção entre os dois vetores
intersecao = np.intersect1d(primeiro_vector, segundo_vector)

# Mostrar os vetores e a interseção
print("Primeiro Vetor:")
print(primeiro_vector)

print("\nSegundo Vetor:")
print(segundo_vector)

print("\nInterseção:")
print(intersecao)

Primeiro Vetor:
[ 5  6  1  3  4  3 -7 -6  9  3 -1 -6 -7  9 -4  0 10 -6 10  0]

Segundo Vetor:
[ -4  -6  10  -7  10 -10  -8   0   5   6   3   5  -7   2  -1 -10   9  -6
   4  -2   1  10  -8  -7  -7]

Interseção:
[-7 -6 -4 -1  0  1  3  4  5  6  9 10]


Resposta: A função np.intersect1d() encontra os elementos únicos que estão presentes em ambos os vetores, e o resultado é a interseção entre os conjuntos representados pelos dois vetores. Neste exemplo, os números -9, -8, -6, -3, 1, 2, 3, 4, 5, 7 e 9 estão presentes em ambos os vetores.

21. Usando ainda as variáveis da pergunta anterior, escreva a instrução que permite obter as posições (índices) em que ambos os vectores coincidem no seu valor (se existirem, claro). Explique ainda a confirmação do resultado.

In [43]:
# Utilizando os vetores da pergunta anterior
primeiro_vector = np.random.randint(-10, 11, size=20)
segundo_vector = np.random.randint(-10, 11, size=25)

# Encontrar os índices onde ambos os vetores coincidem no valor
indices_coincidentes = np.where(np.in1d(primeiro_vector, segundo_vector))

# Mostrar os vetores e os índices onde coincidem
print("Primeiro Vetor:")
print(primeiro_vector)

print("\nSegundo Vetor:")
print(segundo_vector)

print("\nÍndices onde Coincidem:")
print(indices_coincidentes)


Primeiro Vetor:
[  0   7   7   6  -8  -6  -6   5  10 -10   6  -4  -5  -8   0   2   6   6
   8   6]

Segundo Vetor:
[-7 -1  4 -1  1  5  9  9 -4 -4 10  8  4  4 -3  0  8  9 -5  3 -9  2 10 -1
  0]

Índices onde Coincidem:
(array([ 0,  7,  8, 11, 12, 14, 15, 18], dtype=int64),)


Resposta: Neste código, np.in1d(primeiro_vector, segundo_vector) verifica quais elementos do primeiro_vector estão presentes no segundo_vector. np.where() então retorna os índices onde essas condições são verdadeiras.

22. Considere a matriz seguinte...

    <pre>
mat = [[2,8,9,4],
       [9,4,9,4],
       [4,5,9,7],
       [2,9,4,3]]
    </pre>
    
    Usando a função de conversão 'str' do python standard (para converter uma estrutura do Numpy para uma string), e o método 'count' (usado para contar ocorrências de sub-strings), como poderia obter uma contagem da sequência '9, 4' na matriz 'mat'? (escreva o código passo-a-passo de forma a confirmar o resultado intermédio e o resultado final)
    

In [44]:
# Definir a matriz
mat = [[2, 8, 9, 4], [9, 4, 9, 4], [4, 5, 9, 7], [2, 9, 4, 3]]

# Passo 1: Converter a matriz para uma string
mat_str = str(mat)

# Mostrar o resultado intermédio (opcional)
print("Matriz como String:")
print(mat_str)

# Passo 2: Contar a ocorrência da sequência '9, 4' na string
contagem = mat_str.count('9, 4')

# Mostrar o resultado final
print("\nContagem da Sequência '9, 4':", contagem)


Matriz como String:
[[2, 8, 9, 4], [9, 4, 9, 4], [4, 5, 9, 7], [2, 9, 4, 3]]

Contagem da Sequência '9, 4': 4


23. Escreva o código necessário para obter o valor máximo de uma matriz 4x3 à sua escolha.

In [45]:
# Criar uma matriz 4x3
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Obter o valor máximo da matriz
valor_maximo = np.max(matriz)

# Mostrar o resultado
print("Matriz:")
print(matriz)

print("\nValor Máximo da Matriz:", valor_maximo)

Matriz:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Valor Máximo da Matriz: 12


24. Construa uma matriz 5x5 à sua escolha e coloque numa variável com o nome 'mat_5_5' (ex.: pode usar a função **random.randint()**). Construa também um vector com 5 elementos à sua escolha, e coloque numa variável vec_5. Aplique a operação **mat_5_5 + vec_5**, analise o resultado e explique-o por palavras suas.

In [46]:
# Criar a matriz 5x5 com valores aleatórios entre 1 e 10
mat_5_5 = np.random.randint(1, 11, size=(5, 5))

# Criar um vetor com 5 elementos à escolha
vec_5 = np.array([2, 4, 6, 8, 10])

# Aplicar a operação de adição mat_5_5 + vec_5
resultado = mat_5_5 + vec_5

# Mostrar a matriz, o vetor e o resultado da operação
print("Matriz 5x5:")
print(mat_5_5)

print("\nVetor:")
print(vec_5)

print("\nResultado da Operação mat_5_5 + vec_5:")
print(resultado)


Matriz 5x5:
[[1 3 3 9 6]
 [1 8 3 5 1]
 [2 3 8 1 3]
 [4 6 1 6 1]
 [3 3 5 1 9]]

Vetor:
[ 2  4  6  8 10]

Resultado da Operação mat_5_5 + vec_5:
[[ 3  7  9 17 16]
 [ 3 12  9 13 11]
 [ 4  7 14  9 13]
 [ 6 10  7 14 11]
 [ 5  7 11  9 19]]


Resposta: Neste código, foi criada uma matriz 5x5 chamada mat_5_5 com valores aleatórios entre 1 e 10. Também foi feito um vetor chamado vec_5 com cinco elementos escolhidos manualmente. Em seguida, uma operação de adição foi feita entre a matriz e o vetor usando o operador +. A operação soma cada elemento correspondente da matriz e do vetor, resultando em uma nova matriz chamada resultado. O código finaliza mostrando a matriz original, o vetor e o resultado da operação. Essa operação é útil para modificar uma matriz adicionando ou subtraindo valores específicos de cada elemento, proporcionando flexibilidade ao manipular dados.

25. Pesquise a existência de uma função no Numpy para contar o número de elementos com valor '0' (zero) num array de quaisquer dimensões. Construa um vector e uma matriz que contenham alguns valores zero, coloque cada um na sua variável, e use a função para demonstrar o seu funcionamento.

In [47]:
# Construir um vetor com alguns valores zero
vetor = np.array([1, 0, 5, 0, 0, 8, 0])

# Construir uma matriz com alguns valores zero
matriz = np.array([[1, 0, 3], [0, 5, 0], [7, 0, 9]])

# Contar o número de elementos zero no vetor
num_zeros_vetor = len(vetor) - np.count_nonzero(vetor)

# Contar o número de elementos zero na matriz
num_zeros_matriz = matriz.size - np.count_nonzero(matriz)

# Mostrar o vetor, a matriz e o número de elementos zero em cada um
print("Vetor:")
print(vetor)

print("\nMatriz:")
print(matriz)

print("\nNúmero de Elementos Zero no Vetor:", num_zeros_vetor)
print("Número de Elementos Zero na Matriz:", num_zeros_matriz)


Vetor:
[1 0 5 0 0 8 0]

Matriz:
[[1 0 3]
 [0 5 0]
 [7 0 9]]

Número de Elementos Zero no Vetor: 4
Número de Elementos Zero na Matriz: 4
